-- Centralised Onboarding — strengthen division Terms & Conditions to v2.
-- Appends universal clauses (electronic acceptance & IT Act validity, company/grievance
-- details, DPDP Act data protection, payment security & default, GST/TDS indemnity,
-- cancellation & refund, anti-bribery/AML/sanctions, non-solicitation, assignment,
-- notices, limitation of claims, dispute resolution & amendments) plus division-specific
-- clauses (hospital: site/statutory approvals/equipment; interiors: site readiness/price
-- variation), and bumps version to 2026-08-05-v2. This file mirrors the state applied to
-- production via migration 20260805095000 and is idempotent for replay from the v1 seed.

begin;

update public.onboarding_terms set body = '<h2>Digital Marketing &amp; Services — Client Engagement Terms &amp; Conditions</h2>
<p>These Terms and Conditions (&ldquo;Terms&rdquo;) govern the engagement between Varada Nexus Private Limited (&ldquo;Company&rdquo;) and the client completing this onboarding (&ldquo;Client&rdquo;) for digital marketing, creative, and related services (the &ldquo;Services&rdquo;). By accepting these Terms you confirm you are authorised to bind the Client and that the information and documents provided are true, complete and current.</p>
<h3>1. Definitions</h3><p>&ldquo;Deliverables&rdquo; means the campaigns, content, creatives, reports and services agreed with the Client. &ldquo;Client Materials&rdquo; means brand assets, credentials and content the Client provides.</p>
<h3>2. Scope of Services</h3><p>The Company provides the Services described in each agreed proposal, retainer or work order (&ldquo;Order&rdquo;). These Terms apply to every Order and prevail in case of conflict unless a signed Order states otherwise. The Company may engage vendors and platforms to deliver the Services.</p>
<h3>3. Client Obligations</h3><p>The Client shall provide timely approvals, accurate brand information, lawful Client Materials, and any necessary account access; ensure it holds rights to all Client Materials; and ensure the accuracy of information and documents furnished during onboarding.</p>
<h3>4. Fees, Invoicing and Payment</h3><p>Fees, retainers and media/ad-spend are as set out in the applicable Order. Ad spend and third-party costs are billed at cost or as agreed and are payable in advance where stated. Unless stated otherwise, invoices are payable within seven (7) days. Overdue amounts may attract interest at 1.5% per month or the maximum permitted by law, and Services may be paused.</p>
<h3>5. Taxes</h3><p>Fees are exclusive of GST and other applicable taxes, which the Client shall bear.</p>
<h3>6. Performance and No-Guarantee</h3><p>The Company will apply reasonable skill and care. The Client acknowledges that outcomes of marketing (reach, rankings, leads, conversions) depend on many factors outside the Company&rsquo;s control, and no specific results are guaranteed unless expressly stated in an Order.</p>
<h3>7. Confidentiality</h3><p>Each party shall keep the other&rsquo;s Confidential Information secret and use it only for the engagement. This clause survives termination.</p>
<h3>8. Intellectual Property and Licence</h3><p>Client Materials remain the Client&rsquo;s property. Deliverables created for the Client transfer on full payment, save for the Company&rsquo;s tools, methods and pre-existing materials, which remain the Company&rsquo;s property. The Client grants the Company a licence to use Client Materials to deliver the Services and, unless the Client objects in writing, to reference the engagement as a portfolio credential.</p>
<h3>9. Third-Party Platforms and Compliance</h3><p>The Client is responsible for compliance with the terms and advertising policies of third-party platforms. The Company is not liable for platform actions such as account suspensions or policy changes.</p>
<h3>10. Data Protection</h3><p>Personal data, credentials and documents provided during onboarding are processed solely to deliver the Services, verify identity, and meet legal obligations, in accordance with applicable Indian data-protection law, and stored securely. Access credentials are handled on a need-to-know basis.</p>
<h3>11. Warranties</h3><p>Each party warrants it has authority to enter into these Terms. Save as expressly stated, other warranties are excluded to the extent permitted by law.</p>
<h3>12. Indemnity</h3><p>The Client shall indemnify the Company against claims arising from Client Materials, the Client&rsquo;s instructions, or the Client&rsquo;s breach of these Terms, including intellectual-property and advertising-law claims.</p>
<h3>13. Limitation of Liability</h3><p>Neither party is liable for indirect or consequential loss. The Company&rsquo;s aggregate liability under an Order shall not exceed the fees (excluding pass-through ad spend) paid for that Order in the preceding three (3) months, except for liability that cannot be limited by law.</p>
<h3>14. Term and Termination</h3><p>Retainers continue for the agreed term and renew as stated. Either party may terminate for material breach not cured within thirty (30) days of notice. On termination, accrued fees and committed costs remain payable and access/credentials are returned.</p>
<h3>15. Force Majeure</h3><p>Neither party is liable for delay or failure caused by events beyond its reasonable control.</p>
<h3>16. Governing Law and Dispute Resolution</h3><p>These Terms are governed by the laws of India. Disputes shall be referred to arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996, seated at the Company&rsquo;s registered office, with courts there having exclusive jurisdiction subject to arbitration.</p>
<h3>17. General</h3><p>These Terms with the applicable Order form the entire agreement. Severability and non-waiver apply.</p>
<h2>Additional Terms</h2>
<h3>A. Electronic Acceptance &amp; Validity</h3><p>The Client acknowledges that acceptance of these Terms and submission of the onboarding application by electronic means — including one-time-password (OTP) verification, live-photograph capture, on-screen consent, and the signed and uploaded application form — constitutes a valid, binding and enforceable acceptance under the Information Technology Act, 2000 and applicable law, and shall have the same effect as a physical signature. The Company may retain electronic records (including IP address, device details, timestamps and the captured image) as evidence of acceptance.</p>
<h3>B. Company Details &amp; Grievance Redressal</h3><p>Varada Nexus Private Limited, CIN U43121AP2025PTC117741, GSTIN 37AAKCV7495B1ZV, Registered Office: 80-17-28, K B Nagar, A V A Road, Rajahmundry, Andhra Pradesh 533101. Grievances relating to this application or the processing of personal data may be addressed to the Grievance Officer at grievance@varadanexus.com.</p>
<h3>C. Data Protection (DPDP Act, 2023)</h3><p>Personal data provided is processed on the lawful basis of the Client''s consent and the performance of the engagement, limited to the purposes of onboarding, KYC / identity verification, service delivery, and legal and regulatory compliance. Data is stored securely and retained only as long as necessary or as required by law. The Client (data principal) may exercise rights of access, correction and grievance redressal by contacting the Grievance Officer above. The Company implements reasonable security safeguards and will handle any personal-data breach in accordance with applicable law.</p>
<h3>D. Payment Security &amp; Default</h3><p>Time is of the essence for payment. All undisputed amounts are payable when due; the Client shall not withhold or set off payments on account of any dispute, which shall be pursued separately. On non-payment or delay, the Company may suspend or stop work, withhold deliverables and/or terminate the engagement, without prejudice to its other rights. Advances are non-refundable to the extent of work performed, costs and commitments incurred, and are forfeited on Client-caused cancellation. The Company may set off any sums due to it against amounts payable by it.</p>
<h3>E. Taxes, GST &amp; TDS</h3><p>All fees are exclusive of GST and other applicable taxes, which the Client shall bear. The Client shall provide valid tax documents, deduct tax at source (TDS) at the correct rate and furnish TDS certificates within statutory timelines. The Client shall indemnify the Company for any loss of input tax credit, interest, penalty or demand arising from the Client''s incorrect or delayed tax documentation or compliance.</p>
<h3>F. Cancellation &amp; Refund</h3><p>Purchase orders placed with vendors / manufacturers and made-to-order, bespoke or production items are non-cancellable once initiated. Any refund, where permitted, shall be net of costs incurred, non-cancellable commitments, taxes and a reasonable administration charge. Estimates, timelines and budgets are indicative and become binding only through a signed work order / agreement.</p>
<h3>G. Anti-Bribery, Anti-Corruption &amp; Sanctions</h3><p>Each party shall comply with applicable anti-bribery, anti-corruption, anti-money-laundering and sanctions laws, and shall not offer, give or receive any undue advantage in connection with the engagement. The Client confirms that its funds are from lawful sources and that it is not subject to applicable sanctions.</p>
<h3>H. Non-Solicitation</h3><p>During the engagement and for twelve (12) months thereafter, the Client shall not, directly or indirectly, solicit or employ any personnel or vendor of the Company engaged in providing the Services, without the Company''s prior written consent.</p>
<h3>I. Assignment &amp; Subcontracting</h3><p>The Company may subcontract or engage vendors to perform the Services. The Client shall not assign or transfer its rights or obligations without the Company''s prior written consent.</p>
<h3>J. Notices</h3><p>Notices may be given in writing to the address or email provided in the onboarding application (for the Client) or the Registered Office / grievance email above (for the Company); electronic notices shall be deemed validly served.</p>
<h3>K. Limitation of Claims</h3><p>Any claim arising out of or in connection with the engagement must be notified in writing within six (6) months of the event giving rise to it, failing which the claim shall be deemed waived, to the extent permitted by law.</p>
<h3>L. Dispute Resolution &amp; Amendments</h3><p>The parties shall first attempt to resolve any dispute amicably and in good faith. Failing resolution, the dispute shall be referred to arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996, seated at Rajahmundry, Andhra Pradesh, conducted in English; the courts at Rajahmundry shall have jurisdiction for interim relief. These Terms, together with the applicable work order / agreement, constitute the entire agreement and may be amended only in writing.</p>
', version = '2026-08-05-v2', content_hash = 'onb-digital-services-2026-08-05-v2', is_active = true
where division_code = 'digital-services' and is_active = true;

update public.onboarding_terms set body = '<h2>Hospital Projects — Client Engagement Terms &amp; Conditions</h2>
<p>These Terms and Conditions (&ldquo;Terms&rdquo;) govern the engagement between Varada Nexus Private Limited (&ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) and the client entity completing this onboarding (&ldquo;Client&rdquo;, &ldquo;you&rdquo;) in relation to hospital construction, project management and medical-equipment procurement services (the &ldquo;Services&rdquo;). By accepting these Terms and submitting your onboarding, you confirm that you are duly authorised to bind the Client and that all information and documents provided are true, complete and current.</p>
<h3>1. Definitions</h3><p>&ldquo;Project&rdquo; means the hospital or healthcare-infrastructure works described in the applicable proposal, work order or agreement. &ldquo;Deliverables&rdquo; means the works, goods, equipment and reports to be provided. &ldquo;Confidential Information&rdquo; means non-public information disclosed by either party.</p>
<h3>2. Scope of Services</h3><p>The Company will provide the Services described in each mutually agreed proposal, work order or agreement (&ldquo;Order&rdquo;). These Terms apply to every Order and prevail in case of conflict, unless an Order expressly states otherwise and is signed by both parties. Procurement of medical equipment is subject to manufacturer/supplier availability, specifications and lead times.</p>
<h3>3. Client Obligations</h3><p>The Client shall: (a) provide timely site access, approvals, drawings, licences and clearances; (b) nominate an authorised representative for decisions; (c) obtain and maintain all statutory permissions applicable to the healthcare establishment; and (d) ensure the accuracy of all information and documents furnished during onboarding and thereafter.</p>
<h3>4. Fees, Invoicing and Payment</h3><p>Fees are as set out in the applicable Order. Unless stated otherwise, invoices are payable within fifteen (15) days of the invoice date. Overdue amounts may attract interest at 1.5% per month or the maximum permitted by law, whichever is lower. Amounts are exclusive of taxes.</p>
<h3>5. Taxes</h3><p>All fees are exclusive of GST and other applicable taxes, duties and levies, which the Client shall bear. Each party is responsible for taxes on its own income.</p>
<h3>6. Change Orders</h3><p>Any change to scope, specifications, timelines or quantities shall be documented and may alter fees and schedules. No variation is binding unless recorded in writing.</p>
<h3>7. Confidentiality</h3><p>Each party shall keep the other&rsquo;s Confidential Information secret, use it only for the engagement, and protect it with reasonable care. This clause survives termination.</p>
<h3>8. Intellectual Property</h3><p>Pre-existing intellectual property remains with its owner. Project-specific deliverables prepared for the Client transfer on full payment, save for the Company&rsquo;s tools, know-how and templates, which remain the Company&rsquo;s property.</p>
<h3>9. Data Protection</h3><p>The Company processes personal data and documents provided during onboarding solely to deliver the Services, verify identity, and meet legal obligations, in accordance with applicable Indian data-protection law. Documents are stored securely and shared only with personnel and partners who need them for the engagement.</p>
<h3>10. Warranties</h3><p>Each party warrants it has authority to enter into these Terms. Works and equipment are warranted as stated in the applicable Order and by the relevant manufacturer; save as expressly stated, all other warranties are excluded to the extent permitted by law.</p>
<h3>11. Indemnity</h3><p>The Client shall indemnify the Company against claims arising from the Client&rsquo;s breach, misstatement, or failure to obtain required permissions.</p>
<h3>12. Limitation of Liability</h3><p>Neither party is liable for indirect or consequential loss. The Company&rsquo;s aggregate liability under an Order shall not exceed the fees paid by the Client for that Order in the preceding twelve (12) months, except for liability that cannot be limited by law.</p>
<h3>13. Term and Termination</h3><p>The engagement continues until the Order is completed or terminated. Either party may terminate for material breach not cured within thirty (30) days of notice. Accrued fees and costs remain payable on termination.</p>
<h3>14. Force Majeure</h3><p>Neither party is liable for delay or failure caused by events beyond its reasonable control.</p>
<h3>15. Governing Law and Dispute Resolution</h3><p>These Terms are governed by the laws of India. Disputes shall be referred to arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996, seated at the Company&rsquo;s registered office, with the courts there having exclusive jurisdiction subject to arbitration.</p>
<h3>16. General</h3><p>These Terms, with the applicable Order, form the entire agreement. If any provision is unenforceable, the remainder stands. No waiver is implied by delay.</p>
<h2>Additional Terms</h2>
<h3>A. Electronic Acceptance &amp; Validity</h3><p>The Client acknowledges that acceptance of these Terms and submission of the onboarding application by electronic means — including one-time-password (OTP) verification, live-photograph capture, on-screen consent, and the signed and uploaded application form — constitutes a valid, binding and enforceable acceptance under the Information Technology Act, 2000 and applicable law, and shall have the same effect as a physical signature. The Company may retain electronic records (including IP address, device details, timestamps and the captured image) as evidence of acceptance.</p>
<h3>B. Company Details &amp; Grievance Redressal</h3><p>Varada Nexus Private Limited, CIN U43121AP2025PTC117741, GSTIN 37AAKCV7495B1ZV, Registered Office: 80-17-28, K B Nagar, A V A Road, Rajahmundry, Andhra Pradesh 533101. Grievances relating to this application or the processing of personal data may be addressed to the Grievance Officer at grievance@varadanexus.com.</p>
<h3>C. Data Protection (DPDP Act, 2023)</h3><p>Personal data provided is processed on the lawful basis of the Client''s consent and the performance of the engagement, limited to the purposes of onboarding, KYC / identity verification, service delivery, and legal and regulatory compliance. Data is stored securely and retained only as long as necessary or as required by law. The Client (data principal) may exercise rights of access, correction and grievance redressal by contacting the Grievance Officer above. The Company implements reasonable security safeguards and will handle any personal-data breach in accordance with applicable law.</p>
<h3>D. Payment Security &amp; Default</h3><p>Time is of the essence for payment. All undisputed amounts are payable when due; the Client shall not withhold or set off payments on account of any dispute, which shall be pursued separately. On non-payment or delay, the Company may suspend or stop work, withhold deliverables and/or terminate the engagement, without prejudice to its other rights. Advances are non-refundable to the extent of work performed, costs and commitments incurred, and are forfeited on Client-caused cancellation. The Company may set off any sums due to it against amounts payable by it.</p>
<h3>E. Taxes, GST &amp; TDS</h3><p>All fees are exclusive of GST and other applicable taxes, which the Client shall bear. The Client shall provide valid tax documents, deduct tax at source (TDS) at the correct rate and furnish TDS certificates within statutory timelines. The Client shall indemnify the Company for any loss of input tax credit, interest, penalty or demand arising from the Client''s incorrect or delayed tax documentation or compliance.</p>
<h3>F. Cancellation &amp; Refund</h3><p>Purchase orders placed with vendors / manufacturers and made-to-order, bespoke or production items are non-cancellable once initiated. Any refund, where permitted, shall be net of costs incurred, non-cancellable commitments, taxes and a reasonable administration charge. Estimates, timelines and budgets are indicative and become binding only through a signed work order / agreement.</p>
<h3>G. Anti-Bribery, Anti-Corruption &amp; Sanctions</h3><p>Each party shall comply with applicable anti-bribery, anti-corruption, anti-money-laundering and sanctions laws, and shall not offer, give or receive any undue advantage in connection with the engagement. The Client confirms that its funds are from lawful sources and that it is not subject to applicable sanctions.</p>
<h3>H. Non-Solicitation</h3><p>During the engagement and for twelve (12) months thereafter, the Client shall not, directly or indirectly, solicit or employ any personnel or vendor of the Company engaged in providing the Services, without the Company''s prior written consent.</p>
<h3>I. Assignment &amp; Subcontracting</h3><p>The Company may subcontract or engage vendors to perform the Services. The Client shall not assign or transfer its rights or obligations without the Company''s prior written consent.</p>
<h3>J. Notices</h3><p>Notices may be given in writing to the address or email provided in the onboarding application (for the Client) or the Registered Office / grievance email above (for the Company); electronic notices shall be deemed validly served.</p>
<h3>K. Limitation of Claims</h3><p>Any claim arising out of or in connection with the engagement must be notified in writing within six (6) months of the event giving rise to it, failing which the claim shall be deemed waived, to the extent permitted by law.</p>
<h3>L. Dispute Resolution &amp; Amendments</h3><p>The parties shall first attempt to resolve any dispute amicably and in good faith. Failing resolution, the dispute shall be referred to arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996, seated at Rajahmundry, Andhra Pradesh, conducted in English; the courts at Rajahmundry shall have jurisdiction for interim relief. These Terms, together with the applicable work order / agreement, constitute the entire agreement and may be amended only in writing.</p>

<h3>M. Site, Statutory Approvals &amp; Equipment (Hospital Projects)</h3><p>The Client shall ensure site readiness, access, utilities and safe working conditions, and shall obtain and maintain all statutory approvals and licences applicable to the healthcare establishment and its equipment (including fire, pollution, building, AERB / radiation, drug and clinical-establishment approvals as relevant). Medical equipment and materials are supplied subject to manufacturer / supplier specifications, availability and lead times; warranties are those of the manufacturer and are passed through to the Client; title and risk in goods pass to the Client on delivery. Costs arising from unforeseen site conditions, statutory changes or price escalation (including material and GST rate changes) shall be to the Client''s account.</p>
', version = '2026-08-05-v2', content_hash = 'onb-hospital-projects-2026-08-05-v2', is_active = true
where division_code = 'hospital-projects' and is_active = true;

update public.onboarding_terms set body = '<h2>Interiors — Client Engagement Terms &amp; Conditions</h2>
<p>These Terms and Conditions (&ldquo;Terms&rdquo;) govern the engagement between Varada Nexus Private Limited (&ldquo;Company&rdquo;) and the client completing this onboarding (&ldquo;Client&rdquo;) for interior design, fit-out and related services (the &ldquo;Services&rdquo;). By accepting these Terms you confirm you are authorised to bind the Client and that the information and documents provided are true, complete and current.</p>
<h3>1. Definitions</h3><p>&ldquo;Project&rdquo; means the interiors scope described in the applicable proposal, quotation or work order. &ldquo;Deliverables&rdquo; means designs, drawings, specifications, materials and installation works agreed with the Client.</p>
<h3>2. Scope of Services</h3><p>The Company provides design and/or execution Services described in each mutually agreed proposal, quotation or work order (&ldquo;Order&rdquo;). These Terms apply to every Order and prevail in case of conflict unless an Order signed by both parties states otherwise. Visuals and samples are indicative; natural variation in materials and finishes is not a defect.</p>
<h3>3. Client Obligations</h3><p>The Client shall provide timely site access, approvals, existing drawings, and decisions; obtain society/landlord/statutory permissions where required; and ensure the accuracy of information and documents furnished during onboarding.</p>
<h3>4. Fees, Invoicing and Payment</h3><p>Fees, milestones and advances are as set out in the applicable Order. Unless stated otherwise, milestone invoices are payable within seven (7) days. Work may be paused for overdue payments. Overdue amounts may attract interest at 1.5% per month or the maximum permitted by law.</p>
<h3>5. Taxes</h3><p>Fees are exclusive of GST and other applicable taxes, which the Client shall bear.</p>
<h3>6. Variations and Change Orders</h3><p>Changes to design, materials, quantities or scope shall be recorded in writing and may alter fees and timelines. Bespoke and made-to-order items are non-cancellable once production begins.</p>
<h3>7. Confidentiality</h3><p>Each party shall keep the other&rsquo;s Confidential Information secret and use it only for the engagement. This clause survives termination.</p>
<h3>8. Intellectual Property</h3><p>Design concepts, drawings and documents remain the Company&rsquo;s intellectual property until full payment, upon which a licence to use them for the Project is granted. The Company may photograph completed work for its portfolio unless the Client objects in writing.</p>
<h3>9. Data Protection</h3><p>Personal data and documents provided during onboarding are processed solely to deliver the Services, verify identity, and meet legal obligations, in accordance with applicable Indian data-protection law, and stored securely.</p>
<h3>10. Warranties</h3><p>Workmanship is warranted as stated in the applicable Order. Materials carry the relevant manufacturer&rsquo;s warranty. Save as expressly stated, other warranties are excluded to the extent permitted by law.</p>
<h3>11. Indemnity</h3><p>The Client shall indemnify the Company against claims arising from the Client&rsquo;s breach, misstatement, or failure to obtain required permissions.</p>
<h3>12. Limitation of Liability</h3><p>Neither party is liable for indirect or consequential loss. The Company&rsquo;s aggregate liability under an Order shall not exceed the fees paid for that Order, except for liability that cannot be limited by law.</p>
<h3>13. Term and Termination</h3><p>The engagement continues until the Order is completed or terminated for material breach not cured within thirty (30) days of notice. Costs incurred and works completed remain payable.</p>
<h3>14. Force Majeure</h3><p>Neither party is liable for delay or failure caused by events beyond its reasonable control.</p>
<h3>15. Governing Law and Dispute Resolution</h3><p>These Terms are governed by the laws of India. Disputes shall be referred to arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996, seated at the Company&rsquo;s registered office, with courts there having exclusive jurisdiction subject to arbitration.</p>
<h3>16. General</h3><p>These Terms with the applicable Order form the entire agreement. Severability and non-waiver apply.</p>
<h2>Additional Terms</h2>
<h3>A. Electronic Acceptance &amp; Validity</h3><p>The Client acknowledges that acceptance of these Terms and submission of the onboarding application by electronic means — including one-time-password (OTP) verification, live-photograph capture, on-screen consent, and the signed and uploaded application form — constitutes a valid, binding and enforceable acceptance under the Information Technology Act, 2000 and applicable law, and shall have the same effect as a physical signature. The Company may retain electronic records (including IP address, device details, timestamps and the captured image) as evidence of acceptance.</p>
<h3>B. Company Details &amp; Grievance Redressal</h3><p>Varada Nexus Private Limited, CIN U43121AP2025PTC117741, GSTIN 37AAKCV7495B1ZV, Registered Office: 80-17-28, K B Nagar, A V A Road, Rajahmundry, Andhra Pradesh 533101. Grievances relating to this application or the processing of personal data may be addressed to the Grievance Officer at grievance@varadanexus.com.</p>
<h3>C. Data Protection (DPDP Act, 2023)</h3><p>Personal data provided is processed on the lawful basis of the Client''s consent and the performance of the engagement, limited to the purposes of onboarding, KYC / identity verification, service delivery, and legal and regulatory compliance. Data is stored securely and retained only as long as necessary or as required by law. The Client (data principal) may exercise rights of access, correction and grievance redressal by contacting the Grievance Officer above. The Company implements reasonable security safeguards and will handle any personal-data breach in accordance with applicable law.</p>
<h3>D. Payment Security &amp; Default</h3><p>Time is of the essence for payment. All undisputed amounts are payable when due; the Client shall not withhold or set off payments on account of any dispute, which shall be pursued separately. On non-payment or delay, the Company may suspend or stop work, withhold deliverables and/or terminate the engagement, without prejudice to its other rights. Advances are non-refundable to the extent of work performed, costs and commitments incurred, and are forfeited on Client-caused cancellation. The Company may set off any sums due to it against amounts payable by it.</p>
<h3>E. Taxes, GST &amp; TDS</h3><p>All fees are exclusive of GST and other applicable taxes, which the Client shall bear. The Client shall provide valid tax documents, deduct tax at source (TDS) at the correct rate and furnish TDS certificates within statutory timelines. The Client shall indemnify the Company for any loss of input tax credit, interest, penalty or demand arising from the Client''s incorrect or delayed tax documentation or compliance.</p>
<h3>F. Cancellation &amp; Refund</h3><p>Purchase orders placed with vendors / manufacturers and made-to-order, bespoke or production items are non-cancellable once initiated. Any refund, where permitted, shall be net of costs incurred, non-cancellable commitments, taxes and a reasonable administration charge. Estimates, timelines and budgets are indicative and become binding only through a signed work order / agreement.</p>
<h3>G. Anti-Bribery, Anti-Corruption &amp; Sanctions</h3><p>Each party shall comply with applicable anti-bribery, anti-corruption, anti-money-laundering and sanctions laws, and shall not offer, give or receive any undue advantage in connection with the engagement. The Client confirms that its funds are from lawful sources and that it is not subject to applicable sanctions.</p>
<h3>H. Non-Solicitation</h3><p>During the engagement and for twelve (12) months thereafter, the Client shall not, directly or indirectly, solicit or employ any personnel or vendor of the Company engaged in providing the Services, without the Company''s prior written consent.</p>
<h3>I. Assignment &amp; Subcontracting</h3><p>The Company may subcontract or engage vendors to perform the Services. The Client shall not assign or transfer its rights or obligations without the Company''s prior written consent.</p>
<h3>J. Notices</h3><p>Notices may be given in writing to the address or email provided in the onboarding application (for the Client) or the Registered Office / grievance email above (for the Company); electronic notices shall be deemed validly served.</p>
<h3>K. Limitation of Claims</h3><p>Any claim arising out of or in connection with the engagement must be notified in writing within six (6) months of the event giving rise to it, failing which the claim shall be deemed waived, to the extent permitted by law.</p>
<h3>L. Dispute Resolution &amp; Amendments</h3><p>The parties shall first attempt to resolve any dispute amicably and in good faith. Failing resolution, the dispute shall be referred to arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996, seated at Rajahmundry, Andhra Pradesh, conducted in English; the courts at Rajahmundry shall have jurisdiction for interim relief. These Terms, together with the applicable work order / agreement, constitute the entire agreement and may be amended only in writing.</p>

<h3>M. Site Readiness &amp; Price Variation (Interiors)</h3><p>The Client shall provide timely site access, a ready and safe working area, and required society / landlord / statutory permissions. Delays or additional costs arising from Client-caused delay, unforeseen site conditions, or material and GST price escalation shall be to the Client''s account. Made-to-order and bespoke items are non-cancellable once production begins, and natural variation in materials and finishes is not a defect.</p>
', version = '2026-08-05-v2', content_hash = 'onb-interiors-2026-08-05-v2', is_active = true
where division_code = 'interiors' and is_active = true;

update public.onboarding_terms set body = '<h2>Transport &amp; Logistics — Client Engagement Terms &amp; Conditions</h2>
<p>These Terms and Conditions (&ldquo;Terms&rdquo;) govern the engagement between Varada Nexus Private Limited (&ldquo;Company&rdquo;) and the client completing this onboarding (&ldquo;Client&rdquo;) for transportation and logistics services (the &ldquo;Services&rdquo;). By accepting these Terms you confirm you are authorised to bind the Client and that the information and documents provided are true, complete and current.</p>
<h3>1. Definitions</h3><p>&ldquo;Consignment&rdquo; means goods tendered for carriage. &ldquo;Trip&rdquo; means a movement of a Consignment between agreed points. &ldquo;Freight&rdquo; means the charges for the Services.</p>
<h3>2. Scope of Services</h3><p>The Company arranges and/or provides carriage of goods as described in each agreed rate contract, work order or booking (&ldquo;Order&rdquo;). These Terms apply to every Order and prevail in case of conflict unless a signed Order states otherwise.</p>
<h3>3. Client Obligations</h3><p>The Client shall: (a) accurately declare the nature, weight and value of goods; (b) ensure proper packing, lawful documentation (including e-way bills and invoices) and permits; (c) not tender prohibited or hazardous goods without prior written disclosure and consent; and (d) ensure the accuracy of information and documents furnished during onboarding.</p>
<h3>4. Freight, Invoicing and Payment</h3><p>Freight and charges are as set out in the applicable Order. Detention, loading/unloading, and statutory charges are payable as incurred. Unless stated otherwise, invoices are payable within fifteen (15) days. Overdue amounts may attract interest at 1.5% per month or the maximum permitted by law. The Company may exercise a lien over goods for unpaid dues.</p>
<h3>5. Taxes</h3><p>Fees are exclusive of GST and other applicable taxes, which the Client shall bear. GST on transportation shall be handled in accordance with applicable law.</p>
<h3>6. Delivery, Risk and Claims</h3><p>Estimated transit times are indicative and not guaranteed. Risk in the goods remains with the Client save to the extent of the Company&rsquo;s liability below. Any claim for loss, shortage or damage must be notified in writing within seven (7) days of delivery or scheduled delivery, failing which claims are waived.</p>
<h3>7. Confidentiality</h3><p>Each party shall keep the other&rsquo;s Confidential Information secret and use it only for the engagement. This clause survives termination.</p>
<h3>8. Insurance</h3><p>Unless expressly agreed in writing, the Company does not insure the goods. The Client is responsible for arranging transit insurance for the full value of the Consignment.</p>
<h3>9. Data Protection</h3><p>Personal data and documents provided during onboarding are processed solely to deliver the Services, verify identity, and meet legal obligations, in accordance with applicable Indian data-protection law, and stored securely.</p>
<h3>10. Warranties and Representations</h3><p>The Client warrants it is entitled to tender the goods and that all declarations are accurate. Save as expressly stated, other warranties are excluded to the extent permitted by law.</p>
<h3>11. Indemnity</h3><p>The Client shall indemnify the Company against claims, penalties and losses arising from misdeclaration, unlawful or hazardous goods, defective packing, or breach of these Terms.</p>
<h3>12. Limitation of Liability</h3><p>Neither party is liable for indirect or consequential loss. Save for wilful misconduct, the Company&rsquo;s liability for loss of or damage to goods is limited to the amount of Freight for the relevant Trip or the declared and agreed value, whichever is lower, except where liability cannot be limited by law.</p>
<h3>13. Term and Termination</h3><p>The engagement continues until terminated. Either party may terminate for material breach not cured within thirty (30) days of notice. Accrued Freight and charges remain payable.</p>
<h3>14. Force Majeure</h3><p>Neither party is liable for delay or failure caused by events beyond its reasonable control, including road closures, strikes and natural events.</p>
<h3>15. Governing Law and Dispute Resolution</h3><p>These Terms are governed by the laws of India. Disputes shall be referred to arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996, seated at the Company&rsquo;s registered office, with courts there having exclusive jurisdiction subject to arbitration.</p>
<h3>16. General</h3><p>These Terms with the applicable Order form the entire agreement. Severability and non-waiver apply.</p>
<h2>Additional Terms</h2>
<h3>A. Electronic Acceptance &amp; Validity</h3><p>The Client acknowledges that acceptance of these Terms and submission of the onboarding application by electronic means — including one-time-password (OTP) verification, live-photograph capture, on-screen consent, and the signed and uploaded application form — constitutes a valid, binding and enforceable acceptance under the Information Technology Act, 2000 and applicable law, and shall have the same effect as a physical signature. The Company may retain electronic records (including IP address, device details, timestamps and the captured image) as evidence of acceptance.</p>
<h3>B. Company Details &amp; Grievance Redressal</h3><p>Varada Nexus Private Limited, CIN U43121AP2025PTC117741, GSTIN 37AAKCV7495B1ZV, Registered Office: 80-17-28, K B Nagar, A V A Road, Rajahmundry, Andhra Pradesh 533101. Grievances relating to this application or the processing of personal data may be addressed to the Grievance Officer at grievance@varadanexus.com.</p>
<h3>C. Data Protection (DPDP Act, 2023)</h3><p>Personal data provided is processed on the lawful basis of the Client''s consent and the performance of the engagement, limited to the purposes of onboarding, KYC / identity verification, service delivery, and legal and regulatory compliance. Data is stored securely and retained only as long as necessary or as required by law. The Client (data principal) may exercise rights of access, correction and grievance redressal by contacting the Grievance Officer above. The Company implements reasonable security safeguards and will handle any personal-data breach in accordance with applicable law.</p>
<h3>D. Payment Security &amp; Default</h3><p>Time is of the essence for payment. All undisputed amounts are payable when due; the Client shall not withhold or set off payments on account of any dispute, which shall be pursued separately. On non-payment or delay, the Company may suspend or stop work, withhold deliverables and/or terminate the engagement, without prejudice to its other rights. Advances are non-refundable to the extent of work performed, costs and commitments incurred, and are forfeited on Client-caused cancellation. The Company may set off any sums due to it against amounts payable by it.</p>
<h3>E. Taxes, GST &amp; TDS</h3><p>All fees are exclusive of GST and other applicable taxes, which the Client shall bear. The Client shall provide valid tax documents, deduct tax at source (TDS) at the correct rate and furnish TDS certificates within statutory timelines. The Client shall indemnify the Company for any loss of input tax credit, interest, penalty or demand arising from the Client''s incorrect or delayed tax documentation or compliance.</p>
<h3>F. Cancellation &amp; Refund</h3><p>Purchase orders placed with vendors / manufacturers and made-to-order, bespoke or production items are non-cancellable once initiated. Any refund, where permitted, shall be net of costs incurred, non-cancellable commitments, taxes and a reasonable administration charge. Estimates, timelines and budgets are indicative and become binding only through a signed work order / agreement.</p>
<h3>G. Anti-Bribery, Anti-Corruption &amp; Sanctions</h3><p>Each party shall comply with applicable anti-bribery, anti-corruption, anti-money-laundering and sanctions laws, and shall not offer, give or receive any undue advantage in connection with the engagement. The Client confirms that its funds are from lawful sources and that it is not subject to applicable sanctions.</p>
<h3>H. Non-Solicitation</h3><p>During the engagement and for twelve (12) months thereafter, the Client shall not, directly or indirectly, solicit or employ any personnel or vendor of the Company engaged in providing the Services, without the Company''s prior written consent.</p>
<h3>I. Assignment &amp; Subcontracting</h3><p>The Company may subcontract or engage vendors to perform the Services. The Client shall not assign or transfer its rights or obligations without the Company''s prior written consent.</p>
<h3>J. Notices</h3><p>Notices may be given in writing to the address or email provided in the onboarding application (for the Client) or the Registered Office / grievance email above (for the Company); electronic notices shall be deemed validly served.</p>
<h3>K. Limitation of Claims</h3><p>Any claim arising out of or in connection with the engagement must be notified in writing within six (6) months of the event giving rise to it, failing which the claim shall be deemed waived, to the extent permitted by law.</p>
<h3>L. Dispute Resolution &amp; Amendments</h3><p>The parties shall first attempt to resolve any dispute amicably and in good faith. Failing resolution, the dispute shall be referred to arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996, seated at Rajahmundry, Andhra Pradesh, conducted in English; the courts at Rajahmundry shall have jurisdiction for interim relief. These Terms, together with the applicable work order / agreement, constitute the entire agreement and may be amended only in writing.</p>
', version = '2026-08-05-v2', content_hash = 'onb-transport-2026-08-05-v2', is_active = true
where division_code = 'transport' and is_active = true;

commit;
