-- Centralised Onboarding — strengthen division Terms & Conditions to v3.
-- Appends a universal, pro-Company "Further Terms — Company Protections" appendix
-- (application-not-an-offer / right to decline; consequences of misrepresentation;
-- payments absolute, non-refundable, no set-off; company lien & set-off; full
-- indemnity incl. advocate-client costs; limitation & exclusion of liability with
-- a hard cap as sole remedy; no reliance / entire agreement / precedence of the
-- Company's terms; third-party & manufacturer non-liability; suspension &
-- termination for cause; biometric & live-authentication consent under the IT Act;
-- no waiver / severability / survival; governing law, exclusive Rajahmundry
-- jurisdiction & arbitration). Bumps version to 2026-08-05-v3.
--
-- NOTE: These terms are deliberately protective of the Company. They should be
-- reviewed and countersigned by a qualified advocate before commercial go-live;
-- excessively one-sided clauses can be read down or held unenforceable in India.

begin;

update public.onboarding_terms
set body = body || $ap$
<h3>Onboarding is an Application, Not an Offer; Right to Decline</h3><p>This onboarding, and every detail and document submitted through it, constitutes an application only and does not create any offer, contract, commitment or obligation binding on the Company. The Company may accept, decline, defer, suspend or discontinue the onboarding or the engagement at its sole and absolute discretion, at any time, without assigning any reason and without any liability whatsoever. No binding contract arises unless and until a written work order or service agreement is executed by an authorised officer of the Company and any required advance is received.</p>
<h3>Truthfulness; Consequences of Misrepresentation</h3><p>The Client represents, warrants and undertakes that all information, documents, identifiers and declarations provided are true, complete, accurate, genuine and not misleading, and that the person completing this onboarding is duly authorised to bind the Client. Any misrepresentation, false statement, concealment, forgery, impersonation or omission entitles the Company, at its sole discretion and with immediate effect, to refuse, suspend or terminate the engagement, retain all amounts paid, recover all resulting losses, costs and damages, and report the matter to the appropriate authorities, in each case without any liability to the Company.</p>
<h3>Payments Absolute; No Set-off; Non-Refundable</h3><p>All amounts are payable in full, in cleared funds, without any deduction, withholding, discount, counterclaim or set-off, and time for payment is of the essence. Advances, deposits, retainers, mobilisation and booking amounts are non-refundable to the extent of work performed and costs, taxes and non-cancellable commitments incurred. The Company may appropriate any amount received towards any outstanding dues in any order it decides. Overdue amounts carry interest at 1.5% per month (or the maximum permitted by law) until paid, and the Company may suspend or stop all work while any amount remains overdue.</p>
<h3>Company Lien and Set-off</h3><p>The Company may retain and exercise a general and particular lien over any documents, deliverables, drawings, goods, materials or property in its possession, and may set off any sums owed to it against any amounts payable by it to the Client, until all dues (present or future) are fully cleared.</p>
<h3>Full Indemnity</h3><p>The Client shall indemnify, defend and hold harmless the Company, its holding, subsidiary and affiliate entities, and their respective directors, officers, employees, agents and subcontractors (each an &ldquo;Indemnified Party&rdquo;), on a full-indemnity basis, from and against any and all claims, demands, actions, proceedings, losses, damages, liabilities, fines, penalties, interest, taxes and costs (including legal costs on an advocate-client / solicitor-client basis) suffered or incurred by any Indemnified Party arising out of or in connection with the Client&rsquo;s breach of these Terms, any misrepresentation, negligence, wilful misconduct, wrongful act or omission of the Client, the Client Materials, or the Client&rsquo;s failure to hold or obtain any permission, licence, registration or approval.</p>
<h3>Limitation and Exclusion of Liability</h3><p>To the maximum extent permitted by law, the Company shall not be liable, whether in contract, tort (including negligence), statute or otherwise, for any indirect, incidental, special, consequential, punitive or exemplary loss, or for any loss of profit, revenue, savings, goodwill, reputation, data, business or opportunity, howsoever arising, even if advised of the possibility. The Company&rsquo;s total aggregate liability arising out of or in connection with the engagement shall not exceed the fees actually received by the Company (excluding pass-through ad-spend, taxes and third-party costs) for the specific Order giving rise to the claim in the three (3) months immediately preceding the event, and this cap represents the Client&rsquo;s sole and exclusive remedy. Nothing in these Terms excludes liability that cannot be excluded by law.</p>
<h3>No Reliance; Entire Agreement; Precedence</h3><p>The Client acknowledges that it has entered into the engagement on its own judgment and has not relied on any representation, statement, estimate, brochure, projection or assurance not expressly set out in these Terms and the signed Order, and had the opportunity to obtain independent legal advice. These Terms together with the signed Order constitute the entire agreement between the parties and supersede all prior discussions, proposals and understandings. In the event of any conflict, these Terms prevail unless the signed Order expressly and specifically overrides a particular clause. The Company&rsquo;s terms prevail over, and the Company expressly rejects, any of the Client&rsquo;s terms, conditions or purchase-order terms.</p>
<h3>Third Parties, Vendors and Manufacturers</h3><p>The Company shall not be liable for the acts, omissions, delays, defaults, warranties, specifications, policies or actions of any third party, vendor, manufacturer, supplier, platform, statutory authority or logistics provider. Where goods or equipment are supplied, manufacturer or supplier warranties (if any) are passed through to the Client and are the Client&rsquo;s sole recourse; title and risk pass to the Client on delivery.</p>
<h3>Suspension and Termination for Cause</h3><p>Without prejudice to its other rights, the Company may suspend or terminate the engagement immediately and without liability upon the Client&rsquo;s breach, non-payment, insolvency or apprehended insolvency, misrepresentation, or unlawful or unethical conduct. On suspension or termination for cause, all amounts accrued, committed or falling due become immediately payable, and the Company may withhold and retain deliverables, documents and goods until all dues are cleared.</p>
<h3>Biometric and Live-Authentication Consent</h3><p>The Client and the authorised signatory expressly and voluntarily consent to the capture, processing, storage and retention by the Company of the live-authentication image (photograph), device details, IP address, geolocation coordinates and timestamp collected during onboarding, and agree that these constitute valid identity-verification and acceptance evidence under the Information Technology Act, 2000 and applicable law, may be retained for the duration required by law or the Company&rsquo;s policies, and may be produced and relied upon by the Company in any dispute, audit or legal proceeding.</p>
<h3>No Waiver; Severability; Survival</h3><p>No delay, indulgence or failure by the Company to exercise or enforce any right operates as a waiver of that or any other right. If any provision is held invalid or unenforceable, it shall be read down to the minimum extent necessary or severed, and the remaining provisions continue in full force and effect. Provisions which by their nature should survive termination — including confidentiality, indemnity, limitation and exclusion of liability, payment obligations, intellectual property, and governing law and dispute resolution — survive termination or expiry of the engagement.</p>
<h3>Governing Law, Jurisdiction and Arbitration</h3><p>These Terms are governed by and construed in accordance with the laws of India. Any dispute arising out of or in connection with the engagement shall be referred to and finally resolved by arbitration by a sole arbitrator under the Arbitration and Conciliation Act, 1996, with the seat and venue at Rajamahendravaram (Rajahmundry), Andhra Pradesh, and the proceedings conducted in English. Subject to arbitration, the courts at Rajamahendravaram (Rajahmundry), Andhra Pradesh alone shall have exclusive jurisdiction over any suit, application or proceeding arising out of or relating to the engagement, to the exclusion of all other courts, and the Client irrevocably waives any objection to such venue or on grounds of forum non conveniens.</p>
$ap$,
    version = '2026-08-05-v3',
    content_hash = 'onb-' || division_code || '-2026-08-05-v3'
where is_active = true;

commit;
