services:
  onlyoffice-document-server:
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8082:80"
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: "${ONLYOFFICE_JWT_SECRET}"
      JWT_HEADER: "AuthorizationJwt"
      JWT_IN_BODY: "true"
    volumes:
      - onlyoffice-data:/var/www/onlyoffice/Data
      - onlyoffice-logs:/var/log/onlyoffice
      - onlyoffice-lib:/var/lib/onlyoffice
      - onlyoffice-db:/var/lib/postgresql

volumes:
  onlyoffice-data:
  onlyoffice-logs:
  onlyoffice-lib:
  onlyoffice-db:
