export const generatedContentJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "headline",
    "concept",
    "hook",
    "cta",
    "altText",
    "keywords",
    "suggestedPostingTime",
    "targetAudience",
    "recommendedPlatforms",
    "category",
    "contentType",
    "variants",
    "carouselSlides",
    "reel",
    "imagePrompt",
    "brandAssetInstructions",
    "safetyNotes",
    "safetyReview",
  ],
  properties: {
    headline: { type: "string" },
    concept: { type: "string" },
    hook: { type: "string" },
    cta: { type: "string" },
    altText: { type: "string" },
    keywords: { type: "array", items: { type: "string" } },
    suggestedPostingTime: { type: "string" },
    targetAudience: { type: "string" },
    recommendedPlatforms: { type: "array", items: { type: "string" } },
    category: { type: "string" },
    contentType: { type: "string" },
    variants: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["platform", "caption", "hashtags", "title"],
        properties: {
          platform: { type: "string" },
          caption: { type: "string" },
          hashtags: { type: "array", items: { type: "string" } },
          title: { type: "string" },
        },
      },
    },
    carouselSlides: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["heading", "body"],
        properties: {
          heading: { type: "string" },
          body: { type: "string" },
        },
      },
    },
    reel: {
      type: "object",
      additionalProperties: false,
      required: ["durationSeconds", "scenes", "endingCta", "musicKeywords"],
      properties: {
        durationSeconds: { type: "number" },
        scenes: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["scene", "visual", "voiceover", "overlay", "camera", "broll"],
            properties: {
              scene: { type: "number" },
              visual: { type: "string" },
              voiceover: { type: "string" },
              overlay: { type: "string" },
              camera: { type: "string" },
              broll: { type: "string" },
            },
          },
        },
        endingCta: { type: "string" },
        musicKeywords: { type: "array", items: { type: "string" } },
      },
    },
    imagePrompt: { type: "string" },
    brandAssetInstructions: {
      type: "object",
      additionalProperties: false,
      required: ["logoAsset", "logoPlacement", "watermark", "colours", "typography", "template"],
      properties: {
        logoAsset: { type: "string" }, logoPlacement: { type: "string" },
        watermark: { type: "boolean" }, colours: { type: "array", items: { type: "string" } },
        typography: { type: "string" }, template: { type: "string" },
      },
    },
    safetyNotes: { type: "array", items: { type: "string" } },
    safetyReview: {
      type: "object",
      additionalProperties: false,
      required: ["branding", "language", "claims", "copyright", "issues"],
      properties: {
        branding: { type: "boolean" }, language: { type: "boolean" },
        claims: { type: "boolean" }, copyright: { type: "boolean" },
        issues: { type: "array", items: { type: "string" } },
      },
    },
  },
} as const;
