import { closePortalSupportTicket, createPortalSupportTicket, getPortalSupportTicket, hasPortalSupportSession, listPortalSupportTickets, replyToPortalSupportTicket } from "./portal-support-api.js";

const DEPARTMENTS = [
  ["general","General Support"],["technical","IT & Technical"],["accounts","Central Accounts"],
  ["legal","Legal"],["transportation","Transportation"],["interiors","Interiors"],
  ["digital_services","Digital Marketing & Services"],["communications","Email, WhatsApp & Meetings"],["administration","Administration"]
];
const CATEGORIES = [["technical","Technical issue"],["access","Login or access"],["data","Data correction"],["billing","Billing or payment"],["security","Security concern"],["feature_request","Feature request"],["other","Other"]];
const state = { open:false, tab:"raise", tickets:[], selected:null, loading:false, error:"", success:"" };

function esc(value){return String(value??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function label(value){return String(value||"").replace(/_/g," ");}
function formatTime(value){try{return new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));}catch{return String(value||"-");}}
function sourceModule(){const match=location.pathname.match(/\/modules\/([^/]+)/);return match?.[1]||"external-portal";}
function defaultDepartment(){const path=location.pathname; if(path.includes("transport-"))return"transportation";if(path.includes("interiors-"))return"interiors";if(path.includes("legal-"))return"legal";if(path.includes("marketing-"))return"digital_services";return"general";}
function options(rows,selected){return rows.map(([value,text])=>`<option value="${value}" ${value===selected?"selected":""}>${text}</option>`).join("");}

function raiseView(){return `<form class="portal-support-form" id="portalSupportCreateForm">
  <div class="portal-support-note">Choose the department that should review your request. The central support desk will verify it before assigning an EMS staff member.</div>
  <label>Department<select name="department" required>${options(DEPARTMENTS,defaultDepartment())}</select></label>
  <div class="portal-support-form-grid"><label>Issue type<select name="category">${options(CATEGORIES,"technical")}</select></label><label>Priority<select name="priority"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div>
  <label>Subject<input name="subject" minlength="5" maxlength="180" required placeholder="Short summary of the issue" /></label>
  <label>Details<textarea name="description" minlength="10" maxlength="5000" required placeholder="Explain what happened, what you expected, and any reference number involved."></textarea></label>
  <button class="portal-support-btn is-primary" type="submit">Submit Support Ticket</button>
</form>`;}

function ticketList(){if(state.loading)return'<div class="portal-support-loading">Loading your tickets…</div>';if(!state.tickets.length)return'<div class="portal-support-empty">You have not raised any support tickets yet.</div>';return `<div class="portal-support-list">${state.tickets.map(t=>`<button class="portal-support-card" type="button" data-portal-ticket="${esc(t.id)}"><span><span class="portal-support-pill">${esc(t.ticket_number)}</span> <span class="portal-support-pill">${esc(label(t.status))}</span></span><strong>${esc(t.subject)}</strong><span class="portal-support-meta">${esc(label(t.department))} · ${esc(formatTime(t.last_activity_at))} · ${Number(t.message_count||0)} replies</span></button>`).join("")}</div>`;}

function detailView(){const detail=state.selected;if(!detail?.ticket)return ticketList();const t=detail.ticket;const messages=(detail.messages||[]).map(m=>`<article class="portal-support-message ${m.is_mine?"is-mine":""}"><header><strong>${esc(m.author_name)}</strong><span>${esc(formatTime(m.created_at))}</span></header><p>${esc(m.body)}</p></article>`).join("")||'<div class="portal-support-empty">No replies yet.</div>';return `<div class="portal-support-detail"><button class="portal-support-btn" id="portalSupportBack" type="button">← My Tickets</button><h3>${esc(t.subject)}</h3><p><span class="portal-support-pill">${esc(t.ticket_number)}</span> <span class="portal-support-pill">${esc(label(t.status))}</span> <span class="portal-support-pill">${esc(label(t.department))}</span></p><p class="portal-support-description">${esc(t.description)}</p><div class="portal-support-timeline">${messages}</div>${t.status==="closed"?'<div class="portal-support-success">This ticket is closed.</div>':`<form class="portal-support-form" id="portalSupportReplyForm"><label>Reply<textarea name="body" maxlength="5000" required placeholder="Add information or respond to support"></textarea></label><button class="portal-support-btn is-primary" type="submit">Send Reply</button></form><button class="portal-support-btn" id="portalSupportCloseTicket" type="button" style="margin-top:.7rem">Close Ticket</button>`}</div>`;}

function render(){document.querySelector("#portalSupportRoot")?.remove();if(!state.open)return;const root=document.createElement("div");root.id="portalSupportRoot";root.innerHTML=`<div class="portal-support-backdrop"><aside class="portal-support-panel" role="dialog" aria-modal="true" aria-label="Portal Support"><header class="portal-support-head"><div><span class="portal-support-meta">VARADA NEXUS</span><h2>Support Desk</h2></div><button class="portal-support-close" id="portalSupportClose" type="button">×</button></header><div class="portal-support-tabs"><button class="portal-support-tab ${state.tab==="raise"?"is-active":""}" data-support-tab="raise" type="button">Raise Ticket</button><button class="portal-support-tab ${state.tab==="tickets"?"is-active":""}" data-support-tab="tickets" type="button">My Tickets</button></div><main class="portal-support-body">${state.error?`<div class="portal-support-error">${esc(state.error)}</div>`:""}${state.success?`<div class="portal-support-success">${esc(state.success)}</div>`:""}${state.tab==="raise"?raiseView():detailView()}</main></aside></div>`;document.body.appendChild(root);bind();}

async function loadTickets(){state.loading=true;state.error="";render();try{state.tickets=await listPortalSupportTickets();}catch(error){state.error=error?.message||"Could not load support tickets.";}finally{state.loading=false;render();}}
async function selectTicket(id){state.loading=true;render();try{state.selected=await getPortalSupportTicket(id);}catch(error){state.error=error?.message||"Could not open ticket.";}finally{state.loading=false;render();}}
function bind(){document.querySelector("#portalSupportClose")?.addEventListener("click",close);document.querySelector(".portal-support-backdrop")?.addEventListener("click",e=>{if(e.target.classList.contains("portal-support-backdrop"))close();});document.querySelectorAll("[data-support-tab]").forEach(b=>b.addEventListener("click",async()=>{state.tab=b.dataset.supportTab;state.selected=null;state.error="";state.success="";render();if(state.tab==="tickets")await loadTickets();}));document.querySelector("#portalSupportCreateForm")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget;const button=form.querySelector("button[type=submit]");button.disabled=true;try{const v=new FormData(form);const result=await createPortalSupportTicket({department:v.get("department"),category:v.get("category"),priority:v.get("priority"),subject:v.get("subject"),description:v.get("description"),sourceModule:sourceModule(),environment:{portal:true,path:location.pathname,userAgent:navigator.userAgent,viewport:`${innerWidth}x${innerHeight}`}});state.success=`Ticket ${result.ticket_number} submitted. It is awaiting support review and staff assignment.`;state.tab="tickets";await loadTickets();}catch(error){state.error=error?.message||"Could not submit ticket.";render();}finally{button.disabled=false;}});document.querySelectorAll("[data-portal-ticket]").forEach(b=>b.addEventListener("click",()=>selectTicket(b.dataset.portalTicket)));document.querySelector("#portalSupportBack")?.addEventListener("click",()=>{state.selected=null;render();});document.querySelector("#portalSupportReplyForm")?.addEventListener("submit",async e=>{e.preventDefault();const v=new FormData(e.currentTarget);try{await replyToPortalSupportTicket(state.selected.ticket.id,v.get("body"));await selectTicket(state.selected.ticket.id);}catch(error){state.error=error?.message||"Could not send reply.";render();}});document.querySelector("#portalSupportCloseTicket")?.addEventListener("click",async()=>{if(!confirm("Close this support ticket?"))return;try{await closePortalSupportTicket(state.selected.ticket.id);await selectTicket(state.selected.ticket.id);}catch(error){state.error=error?.message||"Could not close ticket.";render();}});}
function close(){state.open=false;render();}
function open(){state.open=true;state.error="";state.success="";render();}

export function initPortalSupport(){if(!hasPortalSupportSession()||document.querySelector("#portalSupportLauncher"))return;const button=document.createElement("button");button.id="portalSupportLauncher";button.className="portal-support-launcher";button.type="button";button.innerHTML="<span>?</span> Support";button.addEventListener("click",open);document.body.appendChild(button);document.addEventListener("keydown",e=>{if(e.key==="Escape"&&state.open)close();});}

if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(initPortalSupport,250));else setTimeout(initPortalSupport,250);
