import { MODULES } from "./constants.js";

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  MANAGER: "manager",
  OPERATOR: "operator",
  ACCOUNTS: "accounts",
  CA: "ca",
  AGENT: "agent",
  CONTRACTOR: "contractor",
  CLIENT: "client"
};

export const PERMISSIONS = {
  VIEW: "view",
  CREATE: "create",
  EDIT: "edit",
  DELETE: "delete",
  APPROVE: "approve",
  POST: "post",
  EXPORT: "export",
  CLOSE_PERIOD: "close_period",
  REOPEN_PERIOD: "reopen_period",
  VIEW_AUDIT: "view_audit"
};

const ALL_ADMIN_MODULES = [
  MODULES.DASHBOARD,
  MODULES.USERS,
  MODULES.ROLES,
  MODULES.SETTINGS,
  MODULES.AUDIT,
  MODULES.DIVISIONS,
  MODULES.MASTER_CLIENTS,
  MODULES.MASTER_CONTRACTORS,
  MODULES.MASTER_TRANSPORTERS,
  MODULES.MASTER_AGENTS,
  MODULES.MASTER_COMMODITIES,
  MODULES.MASTER_ROUTES,
  MODULES.MASTER_UNITS,
  MODULES.MASTER_TAX_CODES,
  MODULES.MASTER_DOCUMENT_TYPES
];

const ALL_TRANSPORT_OPERATIONS_MODULES = [
  MODULES.TRANSPORTATION,
  MODULES.TRANSPORT_DASHBOARD,
  MODULES.TRANSPORT_TRUCK_OWNERS,
  MODULES.TRANSPORT_TRUCKS,
  MODULES.TRANSPORT_DRIVERS,
  MODULES.TRANSPORT_ROUTE_MASTER,
  MODULES.TRANSPORT_CLIENTS,
  MODULES.TRANSPORT_TRANSPORTERS,
  MODULES.TRANSPORT_COMMODITIES,
  MODULES.TRANSPORT_CLIENT_MAPPING,
  MODULES.TRANSPORT_TRANSPORTER_MAPPING,
  MODULES.TRANSPORT_TRUCK_AGENT_COMMISSION_MAPPING,
  MODULES.TRANSPORT_RATE_MASTER,
  MODULES.TRANSPORT_TRIP_DASHBOARD,
  MODULES.TRANSPORT_TRIPS,
  MODULES.TRANSPORT_TRIP_EXPENSES,
  MODULES.TRANSPORT_CREATE_TRIP,
  MODULES.TRANSPORT_TRIP_LIST,
  MODULES.TRANSPORT_TRIP_DETAILS,
  MODULES.TRANSPORT_STATUS_TIMELINE
];

const ALL_TRANSPORT_FINANCE_MODULES = [
  MODULES.TRANSPORT_CLIENT_BILLING,
  MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
  MODULES.TRANSPORT_GST_INVOICES,
  MODULES.TRANSPORT_CLIENT_RECEIPTS,
  MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
  MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
  MODULES.TRANSPORT_FINANCE_APPROVAL,
  MODULES.TRANSPORT_FINANCE_POSTING,
  MODULES.TRANSPORT_LEDGER
];

function grant(modules, actions) {
  return Object.fromEntries(modules.map((moduleCode) => [moduleCode, [...actions]]));
}

export const ROLE_MODULE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: {
    ...grant(ALL_ADMIN_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_TRANSPORT_OPERATIONS_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant(ALL_TRANSPORT_FINANCE_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE, PERMISSIONS.APPROVE, PERMISSIONS.POST, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT, PERMISSIONS.CLOSE_PERIOD, PERMISSIONS.REOPEN_PERIOD])
  },
  [ROLES.ADMIN]: {
    ...grant(ALL_ADMIN_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT]),
    ...grant(ALL_TRANSPORT_OPERATIONS_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_GST_INVOICES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
      MODULES.TRANSPORT_FINANCE_APPROVAL,
      MODULES.TRANSPORT_LEDGER
    ], [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant([MODULES.AUDIT], [PERMISSIONS.VIEW, PERMISSIONS.VIEW_AUDIT])
  },
  [ROLES.MANAGER]: {
    ...grant([MODULES.DASHBOARD, MODULES.TRANSPORTATION, MODULES.TRANSPORT_DASHBOARD], [PERMISSIONS.VIEW]),
    ...grant(ALL_TRANSPORT_OPERATIONS_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.APPROVE]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_GST_INVOICES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
      MODULES.TRANSPORT_FINANCE_APPROVAL,
      MODULES.TRANSPORT_LEDGER
    ], [PERMISSIONS.VIEW, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    [MODULES.AUDIT]: [PERMISSIONS.VIEW]
  },
  [ROLES.OPERATOR]: {
    ...grant([MODULES.DASHBOARD, MODULES.TRANSPORTATION, MODULES.TRANSPORT_DASHBOARD], [PERMISSIONS.VIEW]),
    ...grant([
      MODULES.TRANSPORT_TRIPS,
      MODULES.TRANSPORT_CREATE_TRIP,
      MODULES.TRANSPORT_TRIP_LIST,
      MODULES.TRANSPORT_TRIP_DETAILS,
      MODULES.TRANSPORT_STATUS_TIMELINE,
      MODULES.TRANSPORT_TRIP_EXPENSES,
      MODULES.TRANSPORT_TRIP_DASHBOARD,
      MODULES.TRANSPORT_TRUCKS,
      MODULES.TRANSPORT_DRIVERS,
      MODULES.TRANSPORT_CLIENTS,
      MODULES.TRANSPORT_TRANSPORTERS,
      MODULES.TRANSPORT_COMMODITIES,
      MODULES.TRANSPORT_ROUTE_MASTER
    ], [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
      MODULES.TRANSPORT_GST_INVOICES
    ], [PERMISSIONS.VIEW])
  },
  [ROLES.ACCOUNTS]: {
    ...grant([MODULES.DASHBOARD, MODULES.TRANSPORTATION, MODULES.TRANSPORT_DASHBOARD], [PERMISSIONS.VIEW]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_GST_INVOICES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS
    ], [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant([MODULES.TRANSPORT_FINANCE_APPROVAL], [PERMISSIONS.VIEW, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant([MODULES.TRANSPORT_FINANCE_POSTING], [PERMISSIONS.VIEW, PERMISSIONS.POST]),
    ...grant([MODULES.TRANSPORT_LEDGER], [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    [MODULES.AUDIT]: [PERMISSIONS.VIEW, PERMISSIONS.VIEW_AUDIT]
  },
  [ROLES.CA]: {
    ...grant([MODULES.DASHBOARD, MODULES.TRANSPORTATION, MODULES.TRANSPORT_DASHBOARD], [PERMISSIONS.VIEW]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_GST_INVOICES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
      MODULES.TRANSPORT_FINANCE_APPROVAL,
      MODULES.TRANSPORT_LEDGER
    ], [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    [MODULES.AUDIT]: [PERMISSIONS.VIEW, PERMISSIONS.VIEW_AUDIT]
  }
};
