import { MODULES } from "./constants.js";

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  MANAGER: "manager",
  OPERATOR: "operator",
  ACCOUNTS: "accounts",
  ACCOUNTS_MANAGER: "accounts_manager",
  ACCOUNTS_EXECUTIVE: "accounts_executive",
  CA: "ca",
  CFO: "cfo",
  CEO: "ceo",
  AUDITOR: "auditor",
  AGENT: "agent",
  CONTRACTOR: "contractor",
  CLIENT: "client"
};

export const PERMISSIONS = {
  VIEW: "view",
  CREATE: "create",
  EDIT: "edit",
  DELETE: "delete",
  APPROVE: "approve",
  POST: "post",
  EXPORT: "export",
  CLOSE_PERIOD: "close_period",
  REOPEN_PERIOD: "reopen_period",
  VIEW_AUDIT: "view_audit"
};

const ALL_ADMIN_MODULES = [
  MODULES.DASHBOARD,
  MODULES.USERS,
  MODULES.ROLES,
  MODULES.SETTINGS,
  MODULES.DIVISIONS,
  MODULES.MASTER_CLIENTS,
  MODULES.MASTER_CONTRACTORS,
  MODULES.MASTER_TRANSPORTERS,
  MODULES.MASTER_AGENTS,
  MODULES.MASTER_COMMODITIES,
  MODULES.MASTER_ROUTES,
  MODULES.MASTER_UNITS,
  MODULES.MASTER_TAX_CODES,
  MODULES.MASTER_DOCUMENT_TYPES
];

const ALL_TRANSPORT_OPERATIONS_MODULES = [
  MODULES.TRANSPORTATION,
  MODULES.TRANSPORT_DASHBOARD,
  MODULES.TRANSPORT_TRUCK_OWNERS,
  MODULES.TRANSPORT_TRUCKS,
  MODULES.TRANSPORT_DRIVERS,
  MODULES.TRANSPORT_ROUTE_MASTER,
  MODULES.TRANSPORT_CLIENTS,
  MODULES.TRANSPORT_TRANSPORTERS,
  MODULES.TRANSPORT_COMMODITIES,
  MODULES.TRANSPORT_CLIENT_MAPPING,
  MODULES.TRANSPORT_TRANSPORTER_MAPPING,
  MODULES.TRANSPORT_TRUCK_AGENT_COMMISSION_MAPPING,
  MODULES.TRANSPORT_RATE_MASTER,
  MODULES.TRANSPORT_TRIP_DASHBOARD,
  MODULES.TRANSPORT_TRIPS,
  MODULES.TRANSPORT_TRIP_EXPENSES,
  MODULES.TRANSPORT_CREATE_TRIP,
  MODULES.TRANSPORT_TRIP_LIST,
  MODULES.TRANSPORT_TRIP_DETAILS,
  MODULES.TRANSPORT_STATUS_TIMELINE
];

const ALL_TRANSPORT_FINANCE_MODULES = [
  MODULES.TRANSPORT_CLIENT_BILLING,
  MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
  MODULES.TRANSPORT_GST_INVOICES,
  MODULES.TRANSPORT_CLIENT_RECEIPTS,
  MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
  MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
  MODULES.TRANSPORT_FINANCE_APPROVAL,
  MODULES.TRANSPORT_LEDGER
];

const ALL_CENTRAL_ACCOUNTS_PHASE1_MODULES = [
  MODULES.ACCOUNTS,
  MODULES.CENTRAL_ACCOUNTS_DASHBOARD,
  MODULES.CENTRAL_ACCOUNTS_FINANCIAL_DOCUMENTS,
  MODULES.CENTRAL_ACCOUNTS_POSTING_QUEUE
];

const ALL_CENTRAL_ACCOUNTS_PHASE2_MODULES = [
  MODULES.CENTRAL_ACCOUNTS_JOURNALS,
  MODULES.CENTRAL_ACCOUNTS_AUDIT
];

const ALL_CENTRAL_ACCOUNTS_PHASE3_MODULES = [
  MODULES.CENTRAL_ACCOUNTS_RECEIVABLES,
  MODULES.CENTRAL_ACCOUNTS_PAYABLES
];

const ALL_CENTRAL_ACCOUNTS_PHASE4_MODULES = [
  MODULES.CENTRAL_ACCOUNTS_TREASURY
];

const ALL_INTERIORS_PROJECT_MODULES = [
  MODULES.INTERIORS,
  MODULES.INTERIORS_DASHBOARD,
  MODULES.INTERIORS_LEADS,
  MODULES.INTERIORS_CLIENTS,
  MODULES.INTERIORS_PROJECTS,
  MODULES.INTERIORS_PROJECT_DETAIL,
  MODULES.INTERIORS_DESIGNS,
  MODULES.INTERIORS_TEAM_WORKFORCE,
  MODULES.INTERIORS_MATERIALS,
  MODULES.INTERIORS_SITE_UPDATES,
  MODULES.INTERIORS_APPROVALS,
  MODULES.INTERIORS_BILLING,
  MODULES.INTERIORS_REPORTS,
  MODULES.INTERIORS_CLIENT_PORTAL,
  MODULES.INTERIORS_SETTINGS,
  MODULES.INTERIORS_BOQ,
  MODULES.INTERIORS_ESTIMATES,
  MODULES.INTERIORS_QUOTATIONS,
  MODULES.INTERIORS_VARIATION_REQUESTS,
  MODULES.INTERIORS_CHANGE_ORDERS,
  MODULES.INTERIORS_SPACES,
  MODULES.INTERIORS_DESIGN_PACKAGES,
  MODULES.INTERIORS_FINISH_SCHEDULES,
  MODULES.INTERIORS_MATERIAL_SPECS
];

function grant(modules, actions) {
  return Object.fromEntries(modules.map((moduleCode) => [moduleCode, [...actions]]));
}

export const ROLE_MODULE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: {
    ...grant(ALL_ADMIN_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_TRANSPORT_OPERATIONS_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant(ALL_TRANSPORT_FINANCE_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE, PERMISSIONS.APPROVE, PERMISSIONS.POST, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT, PERMISSIONS.CLOSE_PERIOD, PERMISSIONS.REOPEN_PERIOD]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE1_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.APPROVE, PERMISSIONS.POST, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE2_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE3_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE4_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT])
  },
  [ROLES.ADMIN]: {
    ...grant(ALL_ADMIN_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT]),
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_GST_INVOICES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
      MODULES.TRANSPORT_FINANCE_APPROVAL,
      MODULES.TRANSPORT_LEDGER
    ], [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE1_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.APPROVE, PERMISSIONS.POST, PERMISSIONS.EXPORT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE2_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE3_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE4_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant([MODULES.CENTRAL_ACCOUNTS_AUDIT], [PERMISSIONS.VIEW, PERMISSIONS.VIEW_AUDIT])
  },
  [ROLES.MANAGER]: {
    ...grant([MODULES.DASHBOARD, MODULES.TRANSPORTATION, MODULES.TRANSPORT_DASHBOARD], [PERMISSIONS.VIEW]),
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant(ALL_TRANSPORT_OPERATIONS_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.APPROVE]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_GST_INVOICES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
      MODULES.TRANSPORT_FINANCE_APPROVAL,
      MODULES.TRANSPORT_LEDGER
    ], [PERMISSIONS.VIEW, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    [MODULES.CENTRAL_ACCOUNTS_AUDIT]: [PERMISSIONS.VIEW]
  },
  [ROLES.OPERATOR]: {
    ...grant([MODULES.DASHBOARD, MODULES.TRANSPORTATION, MODULES.TRANSPORT_DASHBOARD], [PERMISSIONS.VIEW]),
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT]),
    ...grant([
      MODULES.TRANSPORT_TRIPS,
      MODULES.TRANSPORT_CREATE_TRIP,
      MODULES.TRANSPORT_TRIP_LIST,
      MODULES.TRANSPORT_TRIP_DETAILS,
      MODULES.TRANSPORT_STATUS_TIMELINE,
      MODULES.TRANSPORT_TRIP_EXPENSES,
      MODULES.TRANSPORT_TRIP_DASHBOARD,
      MODULES.TRANSPORT_TRUCKS,
      MODULES.TRANSPORT_DRIVERS,
      MODULES.TRANSPORT_CLIENTS,
      MODULES.TRANSPORT_TRANSPORTERS,
      MODULES.TRANSPORT_COMMODITIES,
      MODULES.TRANSPORT_ROUTE_MASTER
    ], [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
      MODULES.TRANSPORT_GST_INVOICES
    ], [PERMISSIONS.VIEW])
  },
  [ROLES.ACCOUNTS]: {
    ...grant([MODULES.DASHBOARD, MODULES.TRANSPORTATION, MODULES.TRANSPORT_DASHBOARD], [PERMISSIONS.VIEW]),
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_GST_INVOICES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS
    ], [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant([MODULES.TRANSPORT_FINANCE_APPROVAL], [PERMISSIONS.VIEW, PERMISSIONS.APPROVE, PERMISSIONS.POST, PERMISSIONS.EXPORT]),
    ...grant([MODULES.TRANSPORT_LEDGER], [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    [MODULES.CENTRAL_ACCOUNTS_AUDIT]: [PERMISSIONS.VIEW, PERMISSIONS.VIEW_AUDIT]
  },
  [ROLES.ACCOUNTS_MANAGER]: {
    ...grant([MODULES.DASHBOARD, MODULES.ACCOUNTS], [PERMISSIONS.VIEW]),
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant([MODULES.CENTRAL_ACCOUNTS_DASHBOARD, MODULES.CENTRAL_ACCOUNTS_FINANCIAL_DOCUMENTS], [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant([MODULES.CENTRAL_ACCOUNTS_POSTING_QUEUE], [PERMISSIONS.VIEW, PERMISSIONS.POST, PERMISSIONS.EXPORT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE2_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE3_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE4_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT])
  },
  [ROLES.ACCOUNTS_EXECUTIVE]: {
    ...grant([MODULES.DASHBOARD, MODULES.ACCOUNTS], [PERMISSIONS.VIEW]),
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW]),
    ...grant([MODULES.CENTRAL_ACCOUNTS_DASHBOARD, MODULES.CENTRAL_ACCOUNTS_FINANCIAL_DOCUMENTS, MODULES.CENTRAL_ACCOUNTS_POSTING_QUEUE], [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EXPORT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE2_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE3_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE4_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT])
  },
  [ROLES.CA]: {
    ...grant([MODULES.DASHBOARD, MODULES.TRANSPORTATION, MODULES.TRANSPORT_DASHBOARD], [PERMISSIONS.VIEW]),
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant([
      MODULES.TRANSPORT_CLIENT_BILLING,
      MODULES.TRANSPORT_CLIENT_CREDIT_NOTES,
      MODULES.TRANSPORT_GST_INVOICES,
      MODULES.TRANSPORT_CLIENT_RECEIPTS,
      MODULES.TRANSPORT_TRANSPORTER_STATEMENTS,
      MODULES.TRANSPORT_TRANSPORTER_PAYMENTS,
      MODULES.TRANSPORT_FINANCE_APPROVAL,
      MODULES.TRANSPORT_LEDGER
    ], [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant([MODULES.ACCOUNTS, MODULES.CENTRAL_ACCOUNTS_DASHBOARD, MODULES.CENTRAL_ACCOUNTS_FINANCIAL_DOCUMENTS, MODULES.CENTRAL_ACCOUNTS_POSTING_QUEUE], [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE2_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE3_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE4_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    [MODULES.CENTRAL_ACCOUNTS_AUDIT]: [PERMISSIONS.VIEW, PERMISSIONS.VIEW_AUDIT]
  },
  [ROLES.CFO]: {
    ...grant([MODULES.DASHBOARD, MODULES.ACCOUNTS], [PERMISSIONS.VIEW]),
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant([MODULES.CENTRAL_ACCOUNTS_DASHBOARD, MODULES.CENTRAL_ACCOUNTS_FINANCIAL_DOCUMENTS], [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.APPROVE, PERMISSIONS.EXPORT]),
    ...grant([MODULES.CENTRAL_ACCOUNTS_POSTING_QUEUE], [PERMISSIONS.VIEW, PERMISSIONS.POST, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE2_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE3_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant(ALL_CENTRAL_ACCOUNTS_PHASE4_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT])
  },
  [ROLES.CEO]: {
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW]),
    ...grant([MODULES.DASHBOARD, MODULES.ACCOUNTS, MODULES.CENTRAL_ACCOUNTS_DASHBOARD, MODULES.CENTRAL_ACCOUNTS_FINANCIAL_DOCUMENTS, MODULES.CENTRAL_ACCOUNTS_POSTING_QUEUE, MODULES.CENTRAL_ACCOUNTS_JOURNALS, MODULES.CENTRAL_ACCOUNTS_AUDIT, MODULES.CENTRAL_ACCOUNTS_RECEIVABLES, MODULES.CENTRAL_ACCOUNTS_PAYABLES, MODULES.CENTRAL_ACCOUNTS_TREASURY], [PERMISSIONS.VIEW])
  },
  [ROLES.AUDITOR]: {
    ...grant(ALL_INTERIORS_PROJECT_MODULES, [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT]),
    ...grant([MODULES.DASHBOARD, MODULES.ACCOUNTS, MODULES.CENTRAL_ACCOUNTS_DASHBOARD, MODULES.CENTRAL_ACCOUNTS_FINANCIAL_DOCUMENTS, MODULES.CENTRAL_ACCOUNTS_POSTING_QUEUE, MODULES.CENTRAL_ACCOUNTS_JOURNALS, MODULES.CENTRAL_ACCOUNTS_AUDIT, MODULES.CENTRAL_ACCOUNTS_RECEIVABLES, MODULES.CENTRAL_ACCOUNTS_PAYABLES, MODULES.CENTRAL_ACCOUNTS_TREASURY], [PERMISSIONS.VIEW, PERMISSIONS.EXPORT, PERMISSIONS.VIEW_AUDIT])
  }
};
