import { MODULES } from "./constants.js";

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  MANAGER: "manager",
  OPERATOR: "operator",
  ACCOUNTS: "accounts",
  CA: "ca",
  AGENT: "agent",
  CONTRACTOR: "contractor",
  CLIENT: "client"
};

export const PERMISSIONS = {
  VIEW: "view",
  CREATE: "create",
  EDIT: "edit",
  DELETE: "delete",
  APPROVE: "approve"
};

export const ROLE_MODULE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.USERS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.ROLES]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.SETTINGS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.AUDIT]: [PERMISSIONS.VIEW]
  },
  [ROLES.ADMIN]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.USERS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT],
    [MODULES.ROLES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.SETTINGS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [MODULES.AUDIT]: [PERMISSIONS.VIEW]
  },
  [ROLES.MANAGER]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.USERS]: [PERMISSIONS.VIEW],
    [MODULES.ROLES]: [PERMISSIONS.VIEW],
    [MODULES.SETTINGS]: [PERMISSIONS.VIEW],
    [MODULES.AUDIT]: [PERMISSIONS.VIEW]
  }
};
