// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const encoder = new TextEncoder();
const LAB_EVENTS = ["contact.created","contact.updated","message.received","message.sent","message.status","conversation.created","conversation.updated","campaign.completed"];
function env(name:string){ return Deno.env.get(name) || ""; }
function adminClient(){ return createClient(env("SUPABASE_URL"), env("SUPABASE_SERVICE_ROLE_KEY"), { auth:{ persistSession:false, autoRefreshToken:false } }); }
function cors(req:Request){ const origin=req.headers.get("origin")||""; const allowed=["https://varadanexus.com","https://www.varadanexus.com"].includes(origin)||/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin); return { ...(allowed?{"Access-Control-Allow-Origin":origin}:{}), "Access-Control-Allow-Headers":"content-type, apikey", "Access-Control-Allow-Methods":"POST,OPTIONS", "Cache-Control":"no-store", "Content-Type":"application/json", "Vary":"Origin", "X-Content-Type-Options":"nosniff" }; }
function json(req:Request, body:unknown, status=200){ return new Response(JSON.stringify(body),{status,headers:cors(req)}); }
function randomHex(bytes=32){ return Array.from(crypto.getRandomValues(new Uint8Array(bytes))).map(v=>v.toString(16).padStart(2,"0")).join(""); }
async function sha256(value:string){ const digest=await crypto.subtle.digest("SHA-256",encoder.encode(value)); return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,"0")).join(""); }
function b64(bytes:Uint8Array){ let binary=""; bytes.forEach(v=>binary+=String.fromCharCode(v)); return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,""); }
function unb64(value:string){ const raw=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"="); return Uint8Array.from(atob(raw),c=>c.charCodeAt(0)); }
async function secretKey(){ const material=env("WHATSAPP_PLATFORM_TOKEN_ENCRYPTION_KEY"); if(material.length<32) throw new Error("Integration Lab encryption is not configured."); const digest=await crypto.subtle.digest("SHA-256",encoder.encode(`developer-integrations:${material}`)); return crypto.subtle.importKey("raw",digest,"AES-GCM",false,["encrypt","decrypt"]); }
async function encrypt(value:string){ const iv=crypto.getRandomValues(new Uint8Array(12)); const encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv},await secretKey(),encoder.encode(value)); return `v1.${b64(iv)}.${b64(new Uint8Array(encrypted))}`; }
async function decrypt(value:string){ const [version,iv,data]=String(value||"").split("."); if(version!=="v1") throw new Error("Integration Lab credential is invalid."); const clear=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(iv)},await secretKey(),unb64(data)); return new TextDecoder().decode(clear); }
async function hmac(secret:string,value:string){ const key=await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]); const digest=await crypto.subtle.sign("HMAC",key,encoder.encode(value)); return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,"0")).join(""); }
function equal(a:string,b:string){ if(!a||a.length!==b.length)return false; let d=0; for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i); return d===0; }
async function session(admin:any,token:unknown){ const value=String(token||""); if(!/^[a-f0-9]{64}$/i.test(value))throw new Error("Unauthorized"); const {data,error}=await admin.rpc("whatsapp_platform_validate_session",{p_session_token:value}); const row=Array.isArray(data)?data[0]:data; if(error||!row?.tenant_id||!["owner","admin"].includes(row.role_code))throw new Error("Only workspace owners and administrators can use Integration Lab."); return row; }
async function labForTenant(admin:any,tenantId:string){ const {data,error}=await admin.from("whatsapp_platform_integration_labs").select("*").eq("tenant_id",tenantId).maybeSingle(); if(error)throw error; return data; }
function labView(lab:any,runs:any[],events:any[]){ return { configured:Boolean(lab), lab:lab?{id:lab.id,status:lab.status,connectionId:lab.connection_id,apiKeyId:lab.api_key_id,webhookEndpointId:lab.webhook_endpoint_id,createdAt:lab.created_at}:null, runs:runs||[], events:events||[] }; }
async function summary(admin:any,customer:any){ const lab=await labForTenant(admin,customer.tenant_id); if(!lab)return labView(null,[],[]); const [{data:runs},{data:events}]=await Promise.all([admin.from("whatsapp_platform_integration_lab_runs").select("id,suite,status,passed_count,failed_count,duration_ms,results,created_at,completed_at").eq("tenant_id",customer.tenant_id).order("created_at",{ascending:false}).limit(20),admin.from("whatsapp_platform_integration_lab_events").select("id,event_id,event_type,signature_valid,received_at").eq("tenant_id",customer.tenant_id).order("received_at",{ascending:false}).limit(20)]); return labView(lab,runs||[],events||[]); }
async function provision(req:Request,admin:any,customer:any,body:any){
  const existing=await labForTenant(admin,customer.tenant_id); if(existing)return summary(admin,customer);
  let connectionQuery=admin.from("whatsapp_platform_connections").select("id,status").eq("tenant_id",customer.tenant_id).eq("status","connected");
  if(body.connectionId)connectionQuery=connectionQuery.eq("id",String(body.connectionId));
  const {data:connections,error:connectionError}=await connectionQuery.limit(1); const connection=connections?.[0]; if(connectionError||!connection)throw new Error("Connect a WhatsApp business number before configuring Integration Lab.");
  const prefix=randomHex(4), apiToken=`vn_live_${prefix}_${randomHex(24)}`, webhookSecret=`whsec_${randomHex(32)}`, receiverToken=randomHex(32);
  const {data:key,error:keyError}=await admin.from("whatsapp_platform_api_keys").insert({tenant_id:customer.tenant_id,name:"EMS Integration Lab",key_prefix:`vn_live_${prefix}`,token_hash:await sha256(apiToken),scopes:["contacts:read","contacts:write","messages:write"],status:"active",created_by:customer.user_id}).select("id").single(); if(keyError)throw keyError;
  const receiverUrl=`${env("SUPABASE_URL").replace(/\/+$/,'')}/functions/v1/whatsapp-platform-integration-lab?receiver=${receiverToken}`;
  const {data:endpoint,error:endpointError}=await admin.from("whatsapp_platform_webhook_endpoints").insert({tenant_id:customer.tenant_id,connection_id:connection.id,software_name:"EMS Integration Lab",name:"Managed integration test receiver",endpoint_url:receiverUrl,max_attempts:4,fallback_max_attempts:0,timeout_ms:10000,signing_secret_ciphertext:await encrypt(webhookSecret),events:LAB_EVENTS,status:"active",created_by:customer.user_id}).select("id").single();
  if(endpointError){ await admin.from("whatsapp_platform_api_keys").delete().eq("id",key.id); throw endpointError; }
  const {error:labError}=await admin.from("whatsapp_platform_integration_labs").insert({tenant_id:customer.tenant_id,connection_id:connection.id,api_key_id:key.id,api_token_ciphertext:await encrypt(apiToken),webhook_endpoint_id:endpoint.id,webhook_secret_ciphertext:await encrypt(webhookSecret),receiver_token_hash:await sha256(receiverToken),created_by:customer.user_id}); if(labError)throw labError;
  return summary(admin,customer);
}
async function receiver(req:Request,admin:any,token:string){ const raw=await req.text(); const {data:lab}=await admin.from("whatsapp_platform_integration_labs").select("*").eq("receiver_token_hash",await sha256(token)).eq("status","active").maybeSingle(); if(!lab)return json(req,{error:"Unknown receiver"},404); const supplied=String(req.headers.get("x-varada-signature")||"").replace(/^sha256=/,""); const valid=equal(supplied,await hmac(await decrypt(lab.webhook_secret_ciphertext),raw)); if(!valid)return json(req,{error:"Invalid signature"},401); const payload=JSON.parse(raw||"{}"); await admin.from("whatsapp_platform_integration_lab_events").upsert({tenant_id:lab.tenant_id,lab_id:lab.id,event_id:String(req.headers.get("x-varada-event-id")||payload.id||crypto.randomUUID()),event_type:String(req.headers.get("x-varada-event")||payload.type||"unknown"),signature_valid:true,payload},{onConflict:"lab_id,event_id",ignoreDuplicates:true}); return json(req,{received:true}); }
async function runCheck(name:string,fn:()=>Promise<any>){ const started=Date.now(); try{ const result=await fn(); return {name,status:"passed",durationMs:Date.now()-started,...result}; }catch(error){ return {name,status:"failed",durationMs:Date.now()-started,message:error instanceof Error?error.message:String(error)}; } }
async function runSafe(req:Request,admin:any,customer:any,body:any){ const lab=await labForTenant(admin,customer.tenant_id); if(!lab)throw new Error("Configure Integration Lab first."); const started=Date.now(); const {data:run,error}=await admin.from("whatsapp_platform_integration_lab_runs").insert({tenant_id:customer.tenant_id,lab_id:lab.id,suite:"safe",status:"running",started_by:customer.user_id}).select("id").single(); if(error)throw error; const base=`${env("SUPABASE_URL").replace(/\/+$/,'')}/functions/v1/whatsapp-platform-api`; const token=await decrypt(lab.api_token_ciphertext);
  const request=async(path:string,auth=true)=>{ const response=await fetch(`${base}${path}`,{headers:auth?{Authorization:`Bearer ${token}`}:{}}); const data=await response.json().catch(()=>({})); return {response,data}; };
  const results=[];
  results.push(await runCheck("Rejects missing API credentials",async()=>{const {response}=await request("/v1/contacts",false); if(response.status!==401)throw new Error(`Expected 401, received ${response.status}`); return {httpStatus:response.status};}));
  results.push(await runCheck("Lists connected WhatsApp numbers",async()=>{const {response,data}=await request("/v1/numbers"); if(!response.ok)throw new Error(data?.error?.message||`HTTP ${response.status}`); return {httpStatus:response.status,count:data.numbers?.length||0,requestId:data.requestId};}));
  results.push(await runCheck("Reads contacts with pagination",async()=>{const {response,data}=await request("/v1/contacts?page=1&pageSize=1"); if(!response.ok)throw new Error(data?.error?.message||`HTTP ${response.status}`); return {httpStatus:response.status,requestId:data.requestId};}));
  results.push(await runCheck("Exposes API request history",async()=>{const {response,data}=await request("/v1/requests?limit=5"); if(!response.ok)throw new Error(data?.error?.message||`HTTP ${response.status}`); return {httpStatus:response.status,count:data.requests?.length||0,requestId:data.requestId};}));
  results.push(await runCheck("Rejects an invalid webhook signature",async()=>{const receiverRow=await admin.from("whatsapp_platform_webhook_endpoints").select("endpoint_url").eq("id",lab.webhook_endpoint_id).single(); const response=await fetch(receiverRow.data.endpoint_url,{method:"POST",headers:{"Content-Type":"application/json","X-Varada-Signature":"sha256=invalid"},body:'{"type":"developer.invalid"}'}); if(response.status!==401)throw new Error(`Expected 401, received ${response.status}`); return {httpStatus:response.status};}));
  results.push(await runCheck("Delivers and verifies a signed webhook",async()=>{const response=await fetch(`${env("SUPABASE_URL").replace(/\/+$/,'')}/functions/v1/whatsapp-platform-messaging`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"test_developer_webhook",sessionToken:body.sessionToken,webhookId:lab.webhook_endpoint_id})}); const data=await response.json().catch(()=>({})); if(!response.ok||!data.delivered)throw new Error(data.error||`HTTP ${response.status}`); return {httpStatus:data.httpStatus,durationMs:data.durationMs};}));
  const passed=results.filter(x=>x.status==="passed").length,failed=results.length-passed,completed=new Date().toISOString(); await admin.from("whatsapp_platform_integration_lab_runs").update({status:failed?"failed":"passed",passed_count:passed,failed_count:failed,duration_ms:Date.now()-started,results,completed_at:completed}).eq("id",run.id); return {run:{id:run.id,status:failed?"failed":"passed",passedCount:passed,failedCount:failed,durationMs:Date.now()-started,results,completedAt:completed}}; }

Deno.serve(async(req)=>{ const admin=adminClient(); if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)}); const url=new URL(req.url); const receiverToken=url.searchParams.get("receiver"); if(receiverToken&&req.method==="POST")return receiver(req,admin,receiverToken); if(req.method!=="POST")return json(req,{error:"Method not allowed"},405); try{ const body=await req.json().catch(()=>({})); const customer=await session(admin,body.sessionToken); if(body.action==="summary")return json(req,await summary(admin,customer)); if(body.action==="provision")return json(req,await provision(req,admin,customer,body)); if(body.action==="run_safe")return json(req,await runSafe(req,admin,customer,body)); return json(req,{error:"Unsupported action"},400); }catch(error){ return json(req,{error:error instanceof Error?error.message:"Integration Lab failed"},400); } });
